_populateWithExampleData: true

# | Skin parts configuration
parts:
  - id: bluzka
    location: body
    variations:
      - file: parts/clothes/bluzka_alex.png
        bodyType: slim
  - id: vest
    location: body
    variations:
      - file: parts/clothes/vest_alex.png
        bodyType: slim
      - file: parts/clothes/vest_steve.png
        bodyType: normal
  - id: legs
    location: legs
    variations:
      - file: parts/clothes/vest_alex.png
        x: 100
        y: 200
