_populateWithExampleData: true

#
# Docstrings explanation:
# [] - optional properties
# <> - mandatory properties
# (val1|val2) - enum

# | Skin parts configuration
#
# Format:
# - id: <part id>
#   location: <(body|legs|head)>
#   group: [group id]
#   variations:
#     - file: <part .png file>
#       bodyType: [(slim|normal)]
#       x: [x coordinate]
#       y: [y coordinate]
#
parts:
  - id: jeans
    location: legs
    group: legs-main
    variations:
      - file: parts/clothes/vest_alex.png
  - id: shorts
    location: legs
    group: legs-main
    variations:
      - file: parts/clothes/vest_alex.png

# | Per-group additional configuration
#
# Format:
# - id: <group id>
#   rules:
#     - [system rule id] [{ optional configuration }]
#
# Example:
# - id: headwear
#   rules:
#     - MaxParts { number: 4 }
#
# List of all rules:
# @todo
groups:
  - id: legs-main
    rules:
      - "MaxParts { number: 1 }"